clear; close all; clc;
%%
% jsonText = [
% '{', ...
% '  "head": {', ...
% '    "id": "hx",', ...
% '    "name": "多频段宽带方位历程分析",', ...
% '    "time": "2025-7-28 23:45:30"', ...
% '  },', ...
% '  "params": {', ...
% '    "fs": "5000",', ...
% '    "t": [0, 10, 790],', ...
% '    "file_name": [', ...
% '      "D:\\MATLAB\\R2024b\\workplace\\DOA\\vector_hydrophone\\测试数据\\testFile\\20221126104650.mat",', ...
% '      "D:\\MATLAB\\R2024b\\workplace\\DOA\\vector_hydrophone\\测试数据\\testFile\\20221128143237.mat"', ...
% '    ],', ...
% '    "ArraySampAlgInd": 2,', ...
% '    "ArraySampAlgParams": [1, 2, 3],', ...
% '    "xyz": [],', ...
% '    "freqRange": [7, 235],', ...
% '    "NFFT": 50000,', ...
% '    "snaptime": 10,', ...
% '    "steptime": 2,', ...
% '    "OutDir": "D:\\MATLAB\\R2024b\\workplace\\DOA\\vector_hydrophone\\测试数据\\testFile",', ...
% '    "algName": "beamforming",', ...
% '    "isLR": 0,', ...
% '    "TimeStartAndEnd": ["20240124090842", "20240124090912"],', ...
% '    "SourceTime": 400', ...
% '  }', ...
% '}' ...
% ];
host = "0.0.0.0";
port = 5566; 
% [jsonText, req] = recv_json_tcp(host, port);
[jsonText, request, response] = udp_recv_and_dispatch();

%% 信号处理
[request, response] = recv_MultiBandWSpatialTimeSpectrum(jsonText);
disp(response);

%% 绘制结果图
% result = load('D:\\MATLAB\\R2024b\\workplace\\DOA\\vector_hydrophone\\测试数据\\testFile\\WSpatialTimeSpectrum.mat');
% theta = result.theta_scan;
% timeAxis = result.Time_scan;
% BtrMatrix = result.xpower_rec_denoise_sum_dB;
% figure;pcolor(theta, timeAxis, BtrMatrix);
% title('宽带历程图');shading interp;colormap(jet);
% xlabel('角度 (度)');ylabel('时间 (s)');